"""Backward-compatible model exports."""

from gim_desktop.model import (
    FamDocument,
    FamProperty,
    FamSection,
    find_related_mod_path,
    GimDocument,
    GimPackage,
    Layer,
    PropertyDocument,
    PropertySection,
    TextProperty,
    can_preview_as_text,
    decode_bytes_auto,
    flatten_layers,
    infer_device_kind,
    load_gim,
    load_gim_package,
    parse_obj_vertices_edges,
    parse_obj_mesh,
    parse_numeric_triplets,
    parse_points_from_binary,
    parse_property_document,
    parse_property_from_bytes,
    save_gim,
)

__all__ = [
    "Layer",
    "GimDocument",
    "load_gim",
    "save_gim",
    "flatten_layers",
    "infer_device_kind",
    "FamProperty",
    "FamSection",
    "FamDocument",
    "find_related_mod_path",
    "GimPackage",
    "load_gim_package",
    "TextProperty",
    "PropertySection",
    "PropertyDocument",
    "parse_property_document",
    "parse_property_from_bytes",
    "can_preview_as_text",
    "decode_bytes_auto",
    "parse_obj_vertices_edges",
    "parse_obj_mesh",
    "parse_numeric_triplets",
    "parse_points_from_binary",
]
